using Sage.Ast;
using Sage.Enums;
using Sage.Interfaces;
using System.Text;

namespace Sage.Core
{
    /// <summary>
    /// Transpiles the Sage Abstract Syntax Tree (AST) into valid, formatted C source code (.c).
    /// Implements the Visitor pattern to handle different node types.
    /// </summary>
    public class CodeGenerator : ICodeGenerator, IAstVisitor<string>
    {
        private int _indent = 0;

        /// <summary>Monotonic counter used to mint unique C temporary identifiers.</summary>
        private int _tempCounter = 0;

        /// <summary>
        /// Gets the current indentation string based on the nesting level.
        /// </summary>
        private string Indent => new(' ', _indent * 4);

        /// <summary>
        /// Generates the complete source code for a C module.
        /// </summary>
        /// <param name="ast">The root program node.</param>
        /// <param name="moduleName">The name of the module (used for header inclusion).</param>
        /// <returns>A string containing the generated C code.</returns>
        public string Generate(ProgramNode ast, string moduleName)
        {
            string bodyCode = ast.Accept(this);

            var sb = new StringBuilder();
            sb.AppendLine("/* --- Generated by Sage Compiler --- */");

            // The C implementation file only includes its own header contract
            sb.AppendLine($"#include \"{moduleName}.h\"");

            sb.AppendLine("\n/* --- Generated Logic --- */");
            sb.Append(bodyCode);

            return sb.ToString();
        }

        /// <summary>
        /// Transpiles a function declaration into a C function implementation.
        /// </summary>
        public string Visit(FunctionDeclarationNode node)
        {
            if (node.IsExtern) return "";

            bool isMain = node.Name.Equals("main", StringComparison.OrdinalIgnoreCase);
            string cReturnType = isMain ? "int" : TypeSystem.ToCType(node.ReturnType);
            string cName = CNaming.ResolveFunctionName(node);

            var sb = new StringBuilder();
            sb.Append($"{Indent}{cReturnType} {cName}(");

            if (node.Parameters.Count == 0)
            {
                sb.Append("void");
            }
            else
            {
                var paramsList = node.Parameters.Select(p => TypeSystem.FormatCParameter(p.Name, p.Type));
                sb.Append(string.Join(", ", paramsList));
            }
            sb.AppendLine(")");

            sb.AppendLine($"{Indent}{{");
            _indent++;

            if (node.Body != null)
            {
                foreach (var stmt in node.Body.Statements)
                    sb.Append(stmt.Accept(this));
            }

            if (isMain)
                sb.AppendLine($"{Indent}return 0;");

            _indent--;
            sb.AppendLine($"{Indent}}}");

            return sb.ToString();
        }

        /// <summary>
        /// Transpiles a function call expression.
        /// </summary>
        public string Visit(FunctionCallNode node)
        {
            string cName = node.Name;
            if (cName.Contains("::"))
            {
                // Handle external namespace calls or internal module scoping
                cName = node.IsExternCall ? cName.Split("::")[1] : cName.Replace("::", "_");
            }
            var cArgs = node.Arguments.Select(a => a.Accept(this));
            return $"{cName}({string.Join(", ", cArgs)})";
        }

        /// <summary>
        /// Transpiles a variable declaration, handling constants and arrays.
        /// </summary>
        public string Visit(VariableDeclarationNode node)
        {
            string prefix = node.IsConstant ? "const " : "";
            string init = node.Initializer != null ? $" = {node.Initializer.Accept(this)}" : "";

            // Safe heap references are represented as pointers in C.
            if (node.IsReference)
            {
                string refType = $"{TypeSystem.ToCType(node.Type)}*";
                return $"{Indent}{prefix}{refType} {node.Name}{init};\n";
            }

            if (TypeSystem.IsArrayType(node.Type))
            {
                string baseType = TypeSystem.ToCType(TypeSystem.GetArrayBaseType(node.Type));
                string size = TypeSystem.GetArraySize(node.Type).ToString();
                if (string.IsNullOrEmpty(init)) init = " = {0}";
                return $"{Indent}{prefix}{baseType} {node.Name}[{size}]{init};\n";
            }

            return $"{Indent}{prefix}{TypeSystem.ToCType(node.Type)} {node.Name}{init};\n";
        }

        /// <summary>
        /// Formats literals (strings, booleans, floats) into C-compatible representations.
        /// </summary>
        public string Visit(LiteralNode node)
        {
            if (node.TypeName == "str") return $"\"{node.Value}\"";
            if (node.TypeName == "b8") return (bool)node.Value! ? "true" : "false";
            if (node.TypeName == "f32")
            {
                string val = node.Value!.ToString()!.Replace(",", ".");
                return val.Contains('.') ? $"{val}f" : $"{val}.0f";
            }
            return node.Value!.ToString()!.Replace(",", ".");
        }

        public string Visit(ProgramNode node)
        {
            var sb = new StringBuilder();
            foreach (var stmt in node.Statements)
            {
                string result = stmt.Accept(this);
                if (!string.IsNullOrEmpty(result)) sb.Append(result);
            }
            return sb.ToString();
        }

        public string Visit(ModuleNode node)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"\n/* Module: {node.Name} */");
            foreach (var member in node.Members)
            {
                if (member is FunctionDeclarationNode func) func.ModuleOwner = node.Name;
                string result = member.Accept(this);
                if (!string.IsNullOrEmpty(result)) sb.Append(result);
            }
            return sb.ToString();
        }

        public string Visit(BlockNode node)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"{Indent}{{");
            _indent++;
            foreach (var stmt in node.Statements) sb.Append(stmt.Accept(this));
            _indent--;
            sb.AppendLine($"{Indent}}}");
            return sb.ToString();
        }

        /// <summary>
        /// Generates a raw assignment expression. 
        /// Note: The semicolon and indentation are handled by ExpressionStatementNode.
        /// </summary>
        public string Visit(AssignmentNode node) => $"{node.Target.Accept(this)} = {node.Expression.Accept(this)}";

        public string Visit(IdentifierNode node) => node.Name.Replace("::", "_");

        public string Visit(ReturnNode node) => $"{Indent}return {node.Expression.Accept(this)};\n";

        public string Visit(ExpressionStatementNode node) => $"{Indent}{node.Expression.Accept(this)};\n";

        public string Visit(UseNode node) => "";

        public string Visit(StructDeclarationNode node) => "";

        public string Visit(ExternBlockNode node) => "";

        public string Visit(ExternTypeNode node) => "";

        /// <summary>An unsafe block carries no runtime cost; it emits a plain scoped C block.</summary>
        public string Visit(UnsafeBlockNode node) => node.Body.Accept(this);

        /// <summary>
        /// Transpiles a safe heap allocation. Uses a GNU statement-expression to allocate,
        /// initialize, and yield a pointer to the new value.
        /// </summary>
        public string Visit(NewExpressionNode node)
        {
            string cType = TypeSystem.ToCType(node.TypeName);
            string tmp = $"_new{_tempCounter++}";

            string initList = node.Fields.Count > 0
                ? "{ " + string.Join(", ", node.Fields.Select(kvp => $".{kvp.Key} = {kvp.Value.Accept(this)}")) + " }"
                : "{0}";

            return $"({{ {cType}* {tmp} = malloc(sizeof({cType})); *{tmp} = ({cType}){initList}; {tmp}; }})";
        }

        /// <summary>Releases a safe heap reference produced by <c>new</c>.</summary>
        public string Visit(DeleteNode node) => $"{Indent}free({node.Target.Accept(this)});\n";

        public string Visit(BinaryExpressionNode node)
        {
            string op = node.Operator switch
            {
                TokenType.Plus => "+",
                TokenType.Minus => "-",
                TokenType.Asterisk => "*",
                TokenType.Slash => "/",
                TokenType.Percent => "%",
                TokenType.EqualEqual => "==",
                TokenType.NotEqual => "!=",
                TokenType.Less => "<",
                TokenType.LessEqual => "<=",
                TokenType.Greater => ">",
                TokenType.GreaterEqual => ">=",
                TokenType.AmpersandAmpersand => "&&",
                TokenType.PipePipe => "||",
                _ => "+"
            };
            return $"({node.Left.Accept(this)} {op} {node.Right.Accept(this)})";
        }

        public string Visit(CastExpressionNode node) => $"(({TypeSystem.ToCType(node.TargetType)}){node.Expression.Accept(this)})";

        public string Visit(IfNode node)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"{Indent}if ({node.Condition.Accept(this)})");
            sb.Append(node.ThenBranch.Accept(this));

            if (node.ElseBranch != null)
            {
                if (node.ElseBranch is IfNode)
                {
                    sb.Append($"{Indent}else ");
                    sb.Append(node.ElseBranch.Accept(this).TrimStart());
                }
                else
                {
                    sb.AppendLine($"{Indent}else");
                    sb.Append(node.ElseBranch.Accept(this));
                }
            }
            return sb.ToString();
        }

        public string Visit(WhileNode node)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"{Indent}while ({node.Condition.Accept(this)})");
            sb.Append(node.Body.Accept(this));
            return sb.ToString();
        }

        public string Visit(ForNode node)
        {
            var sb = new StringBuilder();
            string init = node.Initializer != null ? node.Initializer.Accept(this).Trim().TrimEnd(';') : "";
            string cond = node.Condition != null ? node.Condition.Accept(this) : "";
            string inc = node.Increment != null ? node.Increment.Accept(this).Trim().TrimEnd(';') : "";

            sb.AppendLine($"{Indent}for ({init}; {cond}; {inc})");
            sb.Append(node.Body.Accept(this));
            return sb.ToString();
        }

        public string Visit(UnaryExpressionNode node)
        {
            string op = node.Operator switch
            {
                TokenType.PlusPlus => "++",
                TokenType.Minus => "-",
                TokenType.Bang => "!",
                _ => ""
            };
            return node.IsPostfix ? $"{node.Operand.Accept(this)}{op}" : $"{op}{node.Operand.Accept(this)}";
        }

        /// <summary>
        /// Transpiles interpolated strings into a scoped C block using snprintf and a static buffer.
        /// </summary>
        public string Visit(InterpolatedStringNode node)
        {
            var formatString = new StringBuilder();
            var arguments = new List<string>();

            foreach (var part in node.Parts)
            {
                if (part is LiteralNode lit && lit.TypeName == "str")
                {
                    string safeLiteral = lit.Value!.ToString()!.Replace("%", "%%");
                    formatString.Append(safeLiteral);
                }
                else
                {
                    string specifier;
                    if (!string.IsNullOrEmpty(part.FormatSpecifier))
                    {
                        if (TypeSystem.IsFloatingPoint(part.VariableType!))
                        {
                            if (part.FormatSpecifier.StartsWith('.')) specifier = $"%{part.FormatSpecifier}";
                            else if (part.FormatSpecifier.EndsWith('f')) specifier = $"%.{part.FormatSpecifier}";
                            else specifier = $"%{part.FormatSpecifier}";
                        }
                        else specifier = $"%{part.FormatSpecifier}";
                    }
                    else
                    {
                        specifier = part.VariableType switch
                        {
                            "i32" or "i16" or "i8" => "%d",
                            "u32" or "u16" or "u8" => "%u",
                            "i64" => "%lld",
                            "u64" => "%llu",
                            "f32" or "f64" => "%f",
                            "str" => "%s",
                            _ => "%d"
                        };
                    }
                    formatString.Append(specifier);
                    arguments.Add(part.Accept(this));
                }
            }

            // Each interpolation gets a uniquely named buffer so several interpolated strings can
            // coexist within a single expression without aliasing one another.
            string buf = $"_buf{_tempCounter++}";
            string argsC = arguments.Count > 0 ? ", " + string.Join(", ", arguments) : "";
            return $"({{ static char {buf}[512]; snprintf({buf}, sizeof({buf}), \"{formatString}\"{argsC}); {buf}; }})";
        }

        public string Visit(StructInitializationNode node)
        {
            var sb = new StringBuilder();
            if (!string.IsNullOrEmpty(node.VariableType))
                sb.Append($"({TypeSystem.ToCType(node.VariableType)})");

            sb.Append("{ ");
            var initList = new List<string>();
            foreach (var kvp in node.Fields)
                initList.Add($".{kvp.Key} = {kvp.Value.Accept(this)}");

            sb.Append(string.Join(", ", initList));
            sb.Append(" }");
            return sb.ToString();
        }

        public string Visit(MemberAccessNode node)
        {
            // Safe heap references are pointers under the hood, so their members use '->'.
            string separator = node.Object.IsReference ? "->" : ".";
            return $"{node.Object.Accept(this)}{separator}{node.PropertyName}";
        }

        public string Visit(ArrayInitializationNode node)
        {
            var elements = node.Elements.Select(e => e.Accept(this));
            return $"{{ {string.Join(", ", elements)} }}";
        }

        public string Visit(ArrayAccessNode node) => $"{node.Array.Accept(this)}[{node.Index.Accept(this)}]";
    }
}